services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: lab-adguard
    restart: unless-stopped
    ports:
      - "100.64.0.2:53:53/tcp"
      - "100.64.0.2:53:53/udp"
    networks:
      - lab-proxy
    volumes:
      - /data/homelab/lab/adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    labels:
      caddy: http://dns.lab.skywt
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  lab-proxy:
    external: true
