apiVersion: 1

datasources:
  - name: System Monitoring
    uid: system-monitoring
    type: prometheus
    access: proxy
    orgId: 1
    url: http://lab-prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
